/** A single FMEA draft row generated by the AI or local engine. */
export type FmeaDraftRow = {
  id: string;
  toolRowId: string;
  toolNo: string;
  partDescription: string;
  processStep: string;
  potentialFailureMode: string;
  potentialEffect: string;
  severity: number;
  potentialCause: string;
  occurrence: number;
  currentPreventionControl: string;
  currentDetectionControl: string;
  detection: number;
  rpn: number;
  recommendedAction: string;
  responsibleFunction: string;
  targetDate: string;
  /** Combined historical FMEA and standards checklist entries from PostgreSQL. */
  checklistEntries?: Array<{
    id: string;
    tool_description_normalized: string;
    tool_category: string | null;
    failure_mode: string;
    sub_concern_index: number;
    concern: string;
    recommendation: string;
    supporting_record_count: number;
    supporting_record_ids: string[];
    supporting_failure_ids: number[];
    applicability_scope?: "exact_tool" | "global_process";
    source_types?: Array<
      "historical_fmea" | "product_standard" | "baseline_standard"
    >;
    historical_checklist_ids?: string[];
    supporting_standard_refs?: Array<{
      source_type: "product_standard" | "baseline_standard";
      source_id: string;
      slug?: string;
      title: string;
      source_file?: string | null;
      section?: string;
      reference?: string;
      source_excerpt?: string;
    }>;
    similarity?: number;
  }>;
};

/** Summary metrics for a batch of FMEA results. */
export type FmeaSummary = {
  totalRows: number;
  highConfidence: number;
  mediumConfidence: number;
  lowConfidence: number;
  draftCount: number;
  approvedCount: number;
  rejectedCount: number;
  averageRpn: number;
  highRpnCount: number;
};

/** Filter state for the FMEA results table. */
export type FmeaFilter =
  | "all"
  | "draft"
  | "approved"
  | "rejected"
  | "low-confidence"
  | "high-rpn";
