/** A single FMEA draft row generated by the AI or local engine. */
export type FmeaDraftRow = {
  id: string;
  toolRowId: string;
  toolNo: string;
  partDescription: string;
  processStep: string;
  potentialFailureMode: string;
  potentialEffect: string;
  severity: number;
  potentialCause: string;
  occurrence: number;
  currentPreventionControl: string;
  currentDetectionControl: string;
  detection: number;
  rpn: number;
  recommendedAction: string;
  responsibleFunction: string;
  targetDate: string;
  /** Historical checklist entries from PostgreSQL */
  checklistEntries?: Array<{
    id: string;
    tool_description_normalized: string;
    tool_category: string | null;
    failure_mode: string;
    sub_concern_index: number;
    concern: string;
    recommendation: string;
    supporting_record_count: number;
    supporting_record_ids: string[];
    supporting_failure_ids: number[];
    similarity?: number;
  }>;
};

/** Summary metrics for a batch of FMEA results. */
export type FmeaSummary = {
  totalRows: number;
  highConfidence: number;
  mediumConfidence: number;
  lowConfidence: number;
  draftCount: number;
  approvedCount: number;
  rejectedCount: number;
  averageRpn: number;
  highRpnCount: number;
};

/** Filter state for the FMEA results table. */
export type FmeaFilter =
  | "all"
  | "draft"
  | "approved"
  | "rejected"
  | "low-confidence"
  | "high-rpn";
